### ISSUE TITLE
v2 error

### ISSUE THREAD

**Issue by MGky** [guilhermebkel/gbkel-portfolio#1]
hi ım having an error when installing 
i did npm install and gatsby develop 
error 
\v2\src\screens\Projects\index.js
  59:4  error  Cannot query field "gbkel" on type "Query"  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)
what should ı do

**Comment by guilhermebkel** [comment]
Hello @MGky! 

At first, thanks for giving a look at this repository, I usually store my portfolio versions here and currently I'm working on the **v3** that is based on **Next.js** on the folder **app**.

This error happens because this query is done by getting the data by a production API on the file [**gatsby-node.js**](https://github.com/guilhermebkel/gbkel-portfolio/blob/master/versions/v2/gatsby-node.js). Since the API is currently down, it is giving you this error. What you can do to avoid it is to remove the data get from the Query on **\v2\src\screens\Projects\index.js** and use mocked data to list the projects. 😁

**Comment by MGky** [comment]
thanks
